DELETE http://localhost:3001/api/blogs/5ed4b3fa11e7260b0c1f5f7d
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFsZXhrYW1pbnNraSIsImlkIjoiNWVjZWRhMzgzMmJmNTE1NjM4MmEzNmMwIiwiaWF0IjoxNTkwODg2Mzk3fQ.lpIRnY5OEbD6YK7SoLDIuZ6QycGxnmuaa3_zvx-KisI